name: fashion

packages:
  - app
  - shared
  - domain
  - data
  - initializer
  - resources

command:
  bootstrap:
    usePubspecOverlap: false

scripts:
  bootstrap:
    run: melos pub get
    description: Install dependencies for all packages

  pubget:
    run: melos exec --no-private -- flutter pub get
    description: Run flutter pub get in all packages

  build:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run build_runner in all packages

  analyze:
    run: melos exec -- dart analyze
    description: Run dart analyze in all packages

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  setup:
    run: melos bootstrap && melos build
    description: Full setup - bootstrap and build